#!/usr/bin/env zsh
#
# z4m ssh - SSH with zsh4monkey teleportation
#
# Usage:
#   z4m ssh [ssh-options] [user@]hostname
#
# Supported styles:
#   - :z4m:ssh:HOST enable, send-extra-files, env
#   - :z4m:ssh:HOST ssh-command, term, cwd, interpreter

emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases
autoload -Uz -- -z4m-copy-path-with-excludes -z4m-ssh-parse-env-spec || return 1
-z4m-check-core-params || return

if (( _z4m_dangerous_root )); then
  print -Pru2 -- "%F{3}z4m%f: refusing to %Bssh%b as %F{1}root%f"
  return 1
fi

local -i must_passthrough=0 i expecting_option_value=0 stop_option_processing=0
local -a pos
local -A z4m_ssh_boolean_opts z4m_ssh_other_opts z4m_ssh_passthrough_opts

z4m_ssh_boolean_opts=(
  4 1 6 1 A 1 a 1 C 1 f 1 G 1 g 1 K 1 k 1 M 1 N 1 n 1
  q 1 s 1 T 1 t 1 V 1 v 1 X 1 x 1 Y 1 y 1
)
z4m_ssh_other_opts=(
  B 1 b 1 c 1 D 1 E 1 e 1 F 1 I 1 i 1 J 1 L 1 l 1 m 1
  O 1 o 1 p 1 Q 1 R 1 S 1 W 1 w 1
)
z4m_ssh_passthrough_opts=(
  D 1 G 1 L 1 N 1 O 1 R 1 T 1 V 1 W 1 f 1 n 1 s 1
)

i=1
while (( i <= $# )); do
  local arg=${argv[i]}

  if (( $#pos > 1 || stop_option_processing )); then
    pos+=($i)
    (( ++i ))
    continue
  fi

  if (( expecting_option_value )); then
    expecting_option_value=0
    (( ++i ))
    continue
  fi

  case $arg in
    --force-sync)
      print -Pru2 -- "%F{3}z4m%f: %B--force-sync%b has been removed"
      print -Pru2 -- "%F{3}z4m%f: %Bz4m ssh%b now uses one-shot bootstrap instead of sync state"
      return 1
      ;;
    --)
      stop_option_processing=1
      (( ++i ))
      continue
      ;;
    -?*)
      local cluster=${arg#-}
      local opt
      while [[ -n $cluster ]]; do
        opt=${cluster[1]}
        [[ -n ${z4m_ssh_passthrough_opts[$opt]-} ]] && must_passthrough=1

        if [[ -n ${z4m_ssh_boolean_opts[$opt]-} ]]; then
          cluster=${cluster[2,-1]}
          continue
        fi

        if [[ -n ${z4m_ssh_other_opts[$opt]-} ]]; then
          [[ -z ${cluster[2,-1]} ]] && expecting_option_value=1
          break
        fi

        must_passthrough=1
        break
      done
      (( ++i ))
      ;;
    *)
      pos+=($i)
      (( ++i ))
      ;;
  esac
done

(( expecting_option_value )) && must_passthrough=1
(( $#pos == 1 )) || must_passthrough=1

local z4m_min_version
-z4m-read-version "$Z4M/zsh4monkey/version" || return
z4m_min_version=$REPLY
local -r z4m_min_version

if [[ ! -r $Z4M/z4m.zsh ||
      ! -r $Z4M/zsh4monkey/main.zsh ||
      ! -r $Z4M/zsh4monkey/sc/exec-zsh-i ||
      ! -d $Z4M/zsh4monkey/fn ]]; then
  print -Pru2 -- "%F{3}z4m%f: local %Bzsh4monkey%b core is incomplete under %F{1}$Z4M/zsh4monkey%f"
  print -Pru2 -- "%F{3}z4m%f: expected %Bz4m.zsh%b, %Bmain.zsh%b, %Bsc/exec-zsh-i%b and %Bfn/%b before running %Bssh%b"
  return 1
fi

local -r z4m_ssh_client=${${(%):-%m}:-unknown}
local -r z4m_local_zdotdir=${ZDOTDIR:-$HOME}
local -r z4m_url=${Z4M_URL:-https://raw.githubusercontent.com/arcthur/zsh4monkey/main}

-z4m-ssh-local-package-dirs() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  -z4m-ssh-package-dir-has-payload() {
    emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

    local dir=$1
    local -a entries=($dir/*(N) $dir/.[^.]*(N) $dir/..?*(N))
    (( $#entries )) || return 1
    (( $#entries == 1 )) && [[ ${entries[1]:t} == .system-tool ]] && return 1
    return 0
  }

  -z4m-ssh-package-dir-is-root() {
    emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

    local dir=$1 base=${1:t}
    local -a top_level_files=($dir/*(.N) $dir/.[^.]*(.N) $dir/..?*(.N))
    (( $#top_level_files )) && return 0
    [[ -d $dir/functions || -s $dir/init.zsh || -s $dir/$base.plugin.zsh || -e $dir/.system-tool ]]
  }

  local -aU dirs
  local dir child
  for dir in $Z4M/*(N-/); do
    dir=${dir#$Z4M/}
    case $dir in
      cache|stickycache|tmp|zsh4monkey) continue ;;
    esac

    if -z4m-ssh-package-dir-is-root $Z4M/$dir; then
      -z4m-ssh-package-dir-has-payload $Z4M/$dir || continue
      dirs+=($dir)
      continue
    fi

    for child in $Z4M/$dir/*(N-/); do
      -z4m-ssh-package-dir-is-root $child || continue
      -z4m-ssh-package-dir-has-payload $child || continue
      dirs+=(${child#$Z4M/})
    done
  done
  print -lr -- $dirs
}

-z4m-ssh-get-config-hostname() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  local line
  while IFS= read -r line; do
    [[ $line == 'hostname '* ]] || continue
    REPLY=${line#hostname }
    [[ -n $REPLY ]]
    return
  done < <(command ssh -G "$@" 2>/dev/null)
  return 1
}

-z4m-ssh-zstyle-has-host-specific() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  local style=$1 host=$2 line pattern
  local context=:z4m:ssh:$host
  [[ -n $host ]] || return 1

  [[ -n $(zstyle -L $context $style 2>/dev/null) ]] && return 0

  while IFS= read -r line; do
    local -a words=(${(z)line})
    (( $#words >= 4 )) || continue
    pattern=$words[2]
    [[ $pattern == $context || $pattern == ':z4m:ssh:*' ]] && continue
    [[ $context == $~pattern ]] && return 0
  done < <(zstyle -L ':z4m:ssh:*' $style 2>/dev/null)
  return 1
}

-z4m-ssh-zstyle-order() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  local style=$1
  local host_alias=${z4m_ssh_style_hosts[1]-}
  local host_config=${z4m_ssh_style_hosts[2]-}
  local -aU order

  [[ -n $host_alias ]] || return 1

  -z4m-ssh-zstyle-has-host-specific $style $host_alias && order+=($host_alias)
  if [[ -n $host_config && $host_config != $host_alias ]]; then
    -z4m-ssh-zstyle-has-host-specific $style $host_config && order+=($host_config)
  fi
  order+=($host_alias)
  print -lr -- $order
}

-z4m-ssh-zstyle-a() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  local style=$1 reply_var=$2
  -z4m-ssh-zstyle-read a $style $reply_var
}

-z4m-ssh-zstyle-s() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  local style=$1 reply_var=$2
  -z4m-ssh-zstyle-read s $style $reply_var
}

-z4m-ssh-zstyle-t() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  local style=$1
  -z4m-ssh-zstyle-read t $style
}

-z4m-ssh-zstyle-read() {
  emulate -L zsh -o typeset_silent -o pipe_fail -o no_aliases

  local mode=$1 style=$2 reply_var=${3-} host value
  local -a order
  order=("${(@f)$(-z4m-ssh-zstyle-order $style)}") || return 1
  for host in $order; do
    case $mode in
      a|s)
        if zstyle -$mode :z4m:ssh:$host $style $reply_var; then
          REPLY=$host
          return 0
        fi
        ;;
      t)
        if zstyle -s :z4m:ssh:$host $style value; then
          REPLY=$host
          case ${(L)value} in
            yes|true|on|1) return 0 ;;
            no|false|off|0) return 1 ;;
          esac
          zstyle -t :z4m:ssh:$host $style
          return
        fi
        ;;
    esac
  done
  return 1
}

local z4m_ssh_host=
if (( $#pos == 1 )); then
  local user_host=$*[pos[1]]
  z4m_ssh_host=${${user_host##*@}%%:*}
fi
local -r z4m_ssh_host

[[ -n $z4m_ssh_host ]] || must_passthrough=1

local -aU z4m_ssh_style_hosts
if (( !must_passthrough )); then
  z4m_ssh_style_hosts=($z4m_ssh_host)
  local z4m_ssh_config_host
  if -z4m-ssh-get-config-hostname "$@"; then
    z4m_ssh_config_host=$REPLY
    [[ -n $z4m_ssh_config_host ]] && z4m_ssh_style_hosts+=($z4m_ssh_config_host)
  fi
fi

local -i z4m_ssh_enable=$(( !must_passthrough ))
-z4m-ssh-zstyle-t enable || z4m_ssh_enable=0

local -i mkdir_control_master=0
local default_ssh_command=(command ssh)
if (( z4m_ssh_enable )); then
  mkdir_control_master=1
  default_ssh_command+=(
    -o ControlMaster=auto
    -o ControlPersist=5
    -o ControlPath='~/.ssh/s/%C')
fi

local -a z4m_ssh_command
if ! -z4m-ssh-zstyle-a ssh-command z4m_ssh_command; then
  z4m_ssh_command=($default_ssh_command)
fi

if (( ! $#z4m_ssh_command )); then
  print -Pru2 -- '%F{3}z4m%f: empty %F{1}z4m_ssh_command%f'
  return 1
fi

if [[ $mkdir_control_master == 1 &&
      ${(pj:\0:)z4m_ssh_command} == ${(pj:\0:)default_ssh_command} &&
      ! -d ~/.ssh/s && -n ~(#qNU) ]]; then
  zf_mkdir -pm 700 ~/.ssh/s || return
  {
    >~/.ssh/s/README <<\END
This directory has been created by `z4m ssh`. It stores control sockets
for SSH connections. See ControlMaster, ControlPath and ControlPersist
in `man ssh_config`. This directory must not be writable by anyone other
than the current user.
END
  } || return
fi

local term z4m_ssh_cwd z4m_ssh_interpreter
-z4m-ssh-zstyle-s term term || term=${TERM:/tmux-256color/screen-256color}
-z4m-ssh-zstyle-s cwd z4m_ssh_cwd || z4m_ssh_cwd=
-z4m-ssh-zstyle-s interpreter z4m_ssh_interpreter || z4m_ssh_interpreter=sh
[[ -n $z4m_ssh_interpreter ]] || z4m_ssh_interpreter=sh

if [[ $z4m_ssh_interpreter == *[[:space:]]* ]]; then
  print -Pru2 -- "%F{3}z4m%f: %Binterpreter%b must be a single executable name or absolute path"
  return 1
fi

if (( must_passthrough || !z4m_ssh_enable )); then
  TERM=${term:-$TERM} "${z4m_ssh_command[@]}" "$@"
  return
fi

local -A z4m_ssh_send_files
local -a z4m_ssh_extra_send_from z4m_ssh_extra_send_to z4m_ssh_extra_send_exclude
local -a z4m_ssh_prelude

z4m_ssh_prelude=(
  '"export" Z4M_URL='${(qq)z4m_url}
  ': "${Z4M:=${XDG_CACHE_HOME:-$HOME/.cache}/zsh4monkey}"'
  '"export" Z4M'
  '"export" ZDOTDIR="$HOME"')

z4m_ssh_send_files=(
  $Z4M/z4m.zsh '"$Z4M"/z4m.zsh'
  $Z4M/z4m.zsh.zwc '"$Z4M"/z4m.zsh.zwc'
  $Z4M/zsh4monkey '"$Z4M"/zsh4monkey'
  $z4m_local_zdotdir/.zshenv '"$ZDOTDIR"/.zshenv'
  $z4m_local_zdotdir/.zshenv.zwc '"$ZDOTDIR"/.zshenv.zwc'
  $z4m_local_zdotdir/.zprofile '"$ZDOTDIR"/.zprofile'
  $z4m_local_zdotdir/.zprofile.zwc '"$ZDOTDIR"/.zprofile.zwc'
  $z4m_local_zdotdir/.zshrc '"$ZDOTDIR"/.zshrc'
  $z4m_local_zdotdir/.zshrc.zwc '"$ZDOTDIR"/.zshrc.zwc'
  $z4m_local_zdotdir/.zlogin '"$ZDOTDIR"/.zlogin'
  $z4m_local_zdotdir/.zlogin.zwc '"$ZDOTDIR"/.zlogin.zwc'
  $z4m_local_zdotdir/.zlogout '"$ZDOTDIR"/.zlogout'
  $z4m_local_zdotdir/.zlogout.zwc '"$ZDOTDIR"/.zlogout.zwc')

local package_dir
for package_dir in "${(@f)$(-z4m-ssh-local-package-dirs)}"; do
  z4m_ssh_send_files[$Z4M/$package_dir]='"$Z4M"/'${(qq)package_dir}
done

local file
for file in $z4m_local_zdotdir/.p10k{,-ascii}{,-8color}.zsh(N); do
  z4m_ssh_send_files[$file]='"$ZDOTDIR"/'${(qq)file:t}
done

local -a extra_files
if -z4m-ssh-zstyle-a send-extra-files extra_files; then
  local spec
  local -a parsed_local parsed_remote parsed_exclude
  for spec in $extra_files; do
    parsed_local=()
    parsed_remote=()
    parsed_exclude=()
    -z4m-ssh-parse-copy-spec "$spec" "$z4m_local_zdotdir" parsed_local parsed_remote parsed_exclude || return

    local -i idx
    for idx in {1..$#parsed_local}; do
      z4m_ssh_extra_send_from+=(${parsed_local[idx]})
      z4m_ssh_extra_send_to+=(${parsed_remote[idx]})
      z4m_ssh_extra_send_exclude+=(${parsed_exclude[idx]})
    done
  done
fi

local -a z4m_ssh_env_specs env_specs
if -z4m-ssh-zstyle-a env env_specs; then
  z4m_ssh_env_specs+=($env_specs)
fi

if (( $#z4m_ssh_env_specs )); then
  local spec action key value
  local -a env_order reply
  local -A env_commands

  for spec in $z4m_ssh_env_specs; do
    -z4m-ssh-parse-env-spec "$spec" || return
    action=$reply[1]
    key=$reply[2]
    value=$reply[3]

    case $action in
      copy)
        if [[ -v $key && ${(Pt)key} == scalar* ]]; then
          value=${(P)key}
          env_commands[$key]='"export" '$key'='${(qq)value}
        else
          env_commands[$key]=''
        fi
        ;;
      set)
        env_commands[$key]='"export" '$key'='${(qq)value}
        ;;
      unset)
        env_commands[$key]='"unset" '$key
        ;;
    esac

    (( ${env_order[(Ie)$key]} )) || env_order+=($key)
  done

  for key in $env_order; do
    [[ -n ${env_commands[$key]-} ]] || continue
    z4m_ssh_prelude+=(${env_commands[$key]})
  done
fi

if [[ -n $z4m_ssh_cwd ]]; then
  z4m_ssh_prelude+=('"export" Z4M_SSH_CWD='${(qq)z4m_ssh_cwd})
fi

local src dst
for src in ${(k)z4m_ssh_send_files}; do
  dst=${z4m_ssh_send_files[$src]}
  if [[ -z $src || -z $dst ]]; then
    print -Pru2 -- '%F{3}z4m%f: empty element(s) in %F{1}z4m_ssh_send_files%f'
    return 1
  fi
  if [[ $src == */ ]]; then
    print -Pru2 -- "%F{3}z4m%f: element(s) of %Bz4m_ssh_send_files%b end with %B/%b: %F{1}${src//\%/%%}%f"
    return 1
  fi
done

local tmpdir
zf_mkdir -p -- $Z4M/tmp || return
if (( $+commands[mktemp] )); then
  tmpdir=$(command mktemp -d -- $Z4M/tmp/ssh.XXXXXXXXXX) || return
else
  tmpdir=$Z4M/tmp/ssh.tmp.$sysparams[pid]
  zf_rm -rf -- $tmpdir || return
  zf_mkdir -- $tmpdir || return
fi

{
  local -a indices send_to send_from send_exclude
  local -i index=0
  for src in ${(k)z4m_ssh_send_files}; do
    send_from+=($src)
    send_exclude+=('')
    send_to+=(${z4m_ssh_send_files[$src]})
  done
  for index in {1..$#z4m_ssh_extra_send_from}; do
    send_from+=(${z4m_ssh_extra_send_from[index]})
    send_to+=(${z4m_ssh_extra_send_to[index]})
    send_exclude+=(${z4m_ssh_extra_send_exclude[index]})
  done

  for index in {1..$#send_from}; do
    src=${send_from[index]}
    dst=${send_to[index]}
    local exclude_blob=$send_exclude[index]
    local archive_path=$tmpdir/$index
    [[ -e $src ]] || continue

    if [[ -n $exclude_blob ]]; then
      -z4m-copy-path-with-excludes "$src" "$archive_path" preserve "$exclude_blob" || return
      [[ -e $archive_path || -L $archive_path ]] || continue
      indices+=($index)
      continue
    fi

    local target=${src:P}
    if [[ -z $target(#qN.) && -z $target(#qN/) ]]; then
      print -Pru2 -- "%F{3}z4m%f: unsupported file type: %F{1}${src//\%/%%}%f"
      return 1
    fi
    if [[ ${tmpdir:P} == $target(|/*) ]]; then
      print -Pru2 -- "%F{3}z4m%f: cannot send file: %F{1}${src//\%/%%}%f"
      return 1
    fi
    zf_ln -s -- $target $archive_path || return
    indices+=($index)
  done

  local -a z4m_ssh_run=(
    'if "[" "-f" "$Z4M"/zsh4monkey/sc/exec-zsh-i "-a" "-r" "$Z4M"/zsh4monkey/sc/exec-zsh-i "]"; then
       "." "$Z4M"/zsh4monkey/sc/exec-zsh-i
     else
       >&2 "printf" "\\033[33mz4m\\033[0m: remote bootstrap helper is missing or unreadable: \\033[31m%s\\033[0m\n" "$Z4M"/zsh4monkey/sc/exec-zsh-i
       "exit" "1"
     fi')

  local script=${"$(<$Z4M/zsh4monkey/sc/ssh-bootstrap)"//$'\r'} || return
  script=${script//'^TERM^'/${(qq)term}}
  script=${script//'^MIN_VERSION^'/${(qq)z4m_min_version}}
  script=${script//'^SSH_HOST^'/${(qq)z4m_ssh_host}}
  script=${script//'^SSH_CLIENT^'/${(qq)z4m_ssh_client}}
  script=${script//'^PRELUDE^'/${(F)z4m_ssh_prelude}}
  script=${script//'^SEND_TO^'/${(j: :)send_to}}
  script=${script//'^RUN^'/${(F)z4m_ssh_run}}
  script=${script//'^DUMP_POS^'/${(r:8:: :)${#script}}}

  print -r -- $script >$tmpdir/script || return

  local -a tar_c_opt tar_x_opt
  local tar_v
  if tar_v=$(command tar --version 2>/dev/null) && [[ $tar_v == *'GNU tar'* ]]; then
    tar_c_opt=(--owner=0 --group=0)
    tar_x_opt=(--warning=no-unknown-keyword --warning=no-timestamp --no-same-owner)
  fi
  (( ${#tar_x_opt} )) || tar_x_opt=()

  if (( $#indices )); then
    COPYFILE_DISABLE=1 command tar -C $tmpdir $tar_c_opt -czhf - -- $indices >>$tmpdir/script || return
  fi

  local -a ssh_front upload_args exec_args
  (( pos[1] > 1 )) && ssh_front=("${@[1,pos[1]-1]}")
  upload_args=("${ssh_front[@]}" -T "${@[pos[1],-1]}")
  exec_args=("${ssh_front[@]}" -t "${@[pos[1],-1]}")

  local remote_script=.z4m-ssh.${(%):-%n}.$sysparams[pid].$EPOCHSECONDS.$RANDOM
  local remote_script_exec=${(qq)remote_script}
  local cmd="test -w /tmp && cat >/tmp/$remote_script && echo 1 && exit"
  cmd+=" || "
  cmd+="test ! -e /tmp/$remote_script && cat >~/$remote_script && echo 2"

  local loc
  loc=$("${z4m_ssh_command[@]}" "${upload_args[@]}" $cmd <$tmpdir/script) || return

  case ${loc//[[:space:]]} in
    1)
      remote_script="/tmp/$remote_script"
      remote_script_exec=${(qq)remote_script}
      ;;
    2)
      remote_script_exec='$HOME/'${(qq)remote_script}
      ;;
    *)
      print -Pru2 -- "%F{3}z4m%f: failed to upload bootstrap script"
      return 1
      ;;
  esac

  local remote_exec=${(qq)z4m_ssh_interpreter}' '$remote_script_exec

  TERM=${term:-$TERM} "${z4m_ssh_command[@]}" "${exec_args[@]}" "$remote_exec"
} always {
  zf_rm -rf -- $tmpdir
}
