#!/usr/bin/env zsh

local -i ret

if [[ -v widgets[-z4m-orig-zle-line-finish] ]]; then
  zle -- -z4m-orig-zle-line-finish "$@" || ret=$?
fi

if [[ -v _z4m_redraw_fd ]]; then
  zle -F "$_z4m_redraw_fd"
  exec {_z4m_redraw_fd}>&-
  unset _z4m_redraw_fd
fi

if [[ $BUFFER == *' ' ]] &&
   ! zstyle -t :z4m:history preserve-trailing-whitespace &&
   -z4m-is-valid-list "$PREBUFFER$BUFFER"; then
  BUFFER=${BUFFER%% #}
fi

unset POSTDISPLAY _z4m_autosuggest_buffer _z4m_autosuggestion
if [[ -v region_highlight ]]; then
  _zsh_highlight
fi

# Vi mode: reset cursor to block when command executes
if (( ${+_Z4M_VI_MODE_ENABLED} )); then
  -z4m-set-cursor-shape block
fi

return ret
