#!/usr/bin/env zsh
#
# History-up implementation with backend detection
# Called via -z4m-with-local-history for proper history scope
#

if (( ${_z4m_atuin_up_arrow:-0} )); then
  # Atuin handles up-arrow (v18+ uses atuin-up-search, older uses _atuin_up_search_widget)
  if (( $+widgets[atuin-up-search] )); then
    zle atuin-up-search
  elif (( $+widgets[_atuin_up_search_widget] )); then
    zle _atuin_up_search_widget
  else
    # Atuin widget not found, fall through to substring
    zle history-substring-search-up
  fi
elif (( ${_z4m_substring_search_loaded:-0} )); then
  # Embedded substring search
  zle history-substring-search-up
else
  # Fallback to prefix search
  zle up-line-or-beginning-search
fi
