#!/usr/bin/env zsh

if (( ${+_z4m_redraw_fd} )); then
  zle -F "$_z4m_redraw_fd"
  exec {_z4m_redraw_fd}>&-
  unset _z4m_redraw_fd
fi

if [[ -v region_highlight &&
      ( ${LASTWIDGET-} != accept-line || ${WIDGET-} != zle-line-pre-redraw ) ]]; then
  _zsh_highlight
  -z4m-autosuggest-fetch
fi
