#!/usr/bin/env zsh

emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases

local last=$LASTWIDGET
zle .set-local-history -n $1
shift
{
  () { local -h LASTWIDGET=$last; "$@" } "$@"
} always {
  zle .set-local-history -n 0
}
return 0
