#!/usr/bin/env zsh

emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases

local file=$Z4M_PACKAGE_DIR/forgit.plugin.zsh
[[ -e $file ]] || return 0

local code
code=$(<$file) || return

local orig="
set | awk -F '=' '{ print \$1 }' | grep FORGIT_ | while read -r var; do
    if ! export | grep -q \"\\(^\$var=\\|^export \$var=\\)\"; then
"
local sub='
for var in "${(@)parameters[(I)FORGIT_*]}"; do
    if [[ ${parameters[$var]} != *export* ]]; then
'
print -r -- ${code/$orig/$sub} >$file
