#!/usr/bin/env zsh

if (( ${+_z4m_redraw_fd} )); then
  zle -F "$_z4m_redraw_fd"
  exec {_z4m_redraw_fd}>&-
  unset _z4m_redraw_fd
fi

local -i autosuggest_library_mode=$(( ${+Z4M_ZAS_LIBRARY_MODE} ))
if [[ ${LASTWIDGET-} != accept-line || ${WIDGET-} != zle-line-pre-redraw ]]; then
  (( ${+_z4m_skip_autosuggest_fetch} || ! autosuggest_library_mode )) || -z4m-autosuggest-fetch
  -z4m-highlight-render
fi
