#!/usr/bin/env zsh

emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases

print -Pru2 -- "%F{3}z4m%f: core parameters have unexpectedly changed"
local -a old=(${(0)_z4m_param_sig})
local -a new=(${(0)${(e)_z4m_param_pat}})
local diff_old=(${new:|old})
local diff_new=(${old:|new})
print -Pru2 -- ""
print -Pru2 -- "%F{2}Expected:%f"
print -Pru2 -- ""
print -lru2 -- "  "$^diff_old
print -Pru2 -- ""
print -Pru2 -- "%F{1}Found:%f"
print -Pru2 -- ""
print -lru2 -- "  "$^diff_new
print -Pru2 -- ""
print -Pru2 -- "Restore the parameters or restart Zsh with %F{2}%Uexec%u zsh%f."
