#!/usr/bin/env zsh

if (( ${+_z4m_redraw_fd} )); then
  zle -F "$_z4m_redraw_fd"
  exec {_z4m_redraw_fd}>&-
  unset _z4m_redraw_fd
fi

if [[ ${LASTWIDGET-} != accept-line || ${WIDGET-} != zle-line-pre-redraw ]]; then
  (( ${+_z4m_skip_autosuggest_fetch} )) || -z4m-autosuggest-fetch
  -z4m-highlight-render
fi
