#!/usr/bin/env zsh

local -i ret

if [[ -v widgets[-z4m-orig-zle-line-finish] ]]; then
  zle -- -z4m-orig-zle-line-finish "$@" || ret=$?
fi

if [[ -v _z4m_redraw_fd ]]; then
  zle -F "$_z4m_redraw_fd"
  exec {_z4m_redraw_fd}>&-
  unset _z4m_redraw_fd
fi

if [[ $BUFFER == *' ' ]] &&
   ! zstyle -t :z4m:history preserve-trailing-whitespace &&
   -z4m-is-valid-list "$PREBUFFER$BUFFER"; then
  BUFFER=${BUFFER%% #}
fi

# Record directory-local history indices for history_pwd strategy.
if (( HISTCMD > 0 )) && (( ${+_z4m_dir_cmd_map} || ${+_z4m_dir_history_ids} )); then
  local dir=${(%):-%~}
  (( ${+_z4m_dir_cmd_map} )) && _z4m_dir_cmd_map[$HISTCMD]=$dir

  if (( ${+_z4m_dir_history_ids} )); then
    local -i cap=${_z4m_autosuggest_state[history_pwd_capture_cap]:-1024}
    local -a ids=($HISTCMD ${=_z4m_dir_history_ids[$dir]-})
    (( $#ids > cap )) && ids=("${ids[1,$cap]}")
    _z4m_dir_history_ids[$dir]="${(j: :)ids}"
  fi
fi

-z4m-autosuggest-reset finish
if [[ -v region_highlight ]]; then
  -z4m-highlight-render
fi

# Vi mode: reset cursor to block when command executes
if (( ${+_Z4M_VI_MODE_ENABLED} )); then
  -z4m-set-cursor-shape block
fi

return ret
