#!/usr/bin/env zsh

emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases

local file=$Z4M_PACKAGE_DIR/${Z4M_PACKAGE_NAME:t}.zsh
[[ -e $file ]] || return 0

local code
code=$(<$file) || return

local orig='

'
local sub='

[[ -n ${ZSH_SCRIPT+X}${ZSH_EXECUTION_STRING+X} ]] && return

'
print -r -- ${code/$orig/$sub} >$file
