#!/usr/bin/env zsh

# Populate an associative array (by name) with env propagation limits.
# Usage:
#   local -A limits
#   -z4m-env-propagation-limits limits

emulate -L zsh -o typeset_silent

(( ARGC == 1 )) || return 1

typeset -n out=$1

out=(
  max_b64 100000
  max_payload 65536
  max_lines 4096
  max_vars 512
  max_scalar 4096
  max_elems 512
  max_key 1024
  max_value 4096
  max_line_len 32768
)
