#!/usr/bin/env zsh

local -i ret

if (( ${+widgets[-z4m-orig-zle-line-pre-redraw]} )); then
  zle -- -z4m-orig-zle-line-pre-redraw "$@" || ret=$?
fi

if (( ${+_z4m_substring_search_highlight} )) &&
   [[ ${_history_substring_search_cursor-} != $CURSOR ||
      ${_history_substring_search_result-} != $BUFFER ]]; then
  typeset -g _history_substring_search_result=
  typeset -g _history_substring_search_query_highlight=
  unset _z4m_substring_search_highlight _history_substring_search_cursor
fi

if (( PENDING || KEYS_QUEUED_COUNT )); then
  if (( ! ${+_z4m_redraw_fd} )); then
    typeset -gi _z4m_redraw_fd
    if sysopen -o cloexec -ru _z4m_redraw_fd /dev/null; then
      zle -F $_z4m_redraw_fd -z4m-redraw-buffer
    else
      unset _z4m_redraw_fd
    fi
  fi

  if (( ${+_z4m_highlight_state} )) && (( ${_z4m_highlight_state[overlay_count]:-0} > 0 )); then
    -z4m-highlight-core-strip-overlays || true
  fi

  (( ${+functions[-z4m-autosuggest-core-pre-redraw]} )) || -z4m-autosuggest-core || true
  (( ${+functions[-z4m-autosuggest-core-pre-redraw]} )) && -z4m-autosuggest-core-pre-redraw || true
else
  -z4m-redraw-buffer
fi

return ret
