#!/usr/bin/env zsh

{
  -z4m-cursor-hide
  local f
  for f in chpwd "${chpwd_functions[@]}" precmd "${(@)precmd_functions:#-z4m-direnv-hook}"; do
    [[ "${+functions[$f]}" == 0 ]] || "$f" &>/dev/null || true
  done
  -z4m-highlight-reset prompt
  zle .reset-prompt
  (( ${1:-0} )) || zle -R
} always {
  (( ${1:-0} )) || -z4m-cursor-show
  -z4m-update-dir-history
}
