#!/usr/bin/env zsh

emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases

if [[ $KEYMAP == vicmd && -n ${BUFFER##*$'\n'} ]]; then
  return $(( ${#BUFFER} - 1 ))
else
  return ${#BUFFER}
fi
