#!/usr/bin/env zsh

[[ -v _z4m_tty_fd ]] || return

builtin echoti civis >&$_z4m_tty_fd
local -i pad_lines=$((LINES - 1))
builtin print -rnu $_z4m_tty_fd -- $'\e[H\e[2J'"${(pl:$pad_lines::\n:)}"
builtin zle -I
builtin zle -R
builtin print -rnu $_z4m_tty_fd -- $'\e[3J'
-z4m-cursor-show
