#!/usr/bin/env zsh

emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases
local word buf
repeat ${NUMERIC:-1}; do
  buf=$PREBUFFER$BUFFER
  for word in ${(Z:n:)buf} ''; do
    (( $#buf < $#RBUFFER )) && break
    buf=${${buf##[[:space:]]#}:$#word}
  done
  CURSOR=$(($#BUFFER - $#buf))
  if (( CURSOR > _z4m_cursor_max() )); then
    (( --CURSOR ))
  fi
done
return 0
