#!/usr/bin/env zsh

[[ -v _z4m_tty_fd ]] || return

autoload +X -Uz -- -z4m-present-files -z4m-cursor-show -z4m-find -z4m-fzf -z4m-fzf-version

# Detect fzf version for new features
-z4m-fzf-version 2>/dev/null || true
local -i ver=${_z4m_fzf_version_num:-0}

local -i dot_glob list_types
[[ -o dot_glob   ]] && dot_glob=1
[[ -o list_types ]] && list_types=1

-z4m-set-list-colors :complete:cd:: $list_types
local -i list_colors=$((!$?))

# Check if we can use --walker (fzf 0.48+)
local -i use_walker=0
if (( ver >= 4800 )); then
  local find_cmd
  zstyle -s :z4m:${WIDGET#z4m-} find-command find_cmd
  # Only use walker if no custom find command is specified
  [[ -z $find_cmd ]] && use_walker=1
fi

{
  -z4m-cursor-hide

  local -i first=1
  while true; do
    local -i redraw=0 again=0
    () {
      emulate -L zsh -o typeset_silent -o pipe_fail -o extended_glob \
    -o prompt_percent -o no_prompt_subst -o no_prompt_bang -o no_bg_nice -o no_aliases
      if (( dot_glob )); then
        local dirs=(*(-/DN))
      else
        local dirs=(*(-/N))
      fi
      local non_empty=(${^${dirs}}/*(D-/Y1N:h:t))

      if (( first )); then
        first=0
      elif (( ! $#dirs )); then
        return 0
      fi

      {
        -z4m-show-dots ''

        local -i pct=60
        (( _z4m_can_save_restore_screen )) && pct=100

        local -i height=$(( ! $#non_empty && 100 * ($#dirs + 4) < pct * LINES ? $#dirs + 4 : pct * LINES / 100 ))

        (( height >= 6 )) || (( height = 6 ))
        (( height <= LINES - 1 )) || (( height = LINES - 1 ))

        local opts=(
          --with-nth=2
          --delimiter='\000'
          --ansi
          --exact
          --no-mouse
          --tiebreak=length,begin,index
          --no-multi
          --border=horizontal
        )

        # Path-optimized scoring (fzf 0.59+)
        (( ver >= 5900 )) && opts+=(--scheme=path)

        # Use built-in walker if available (fzf 0.48+), otherwise fall back to find
        if (( use_walker )); then
          local walker_opts='dir'
          (( dot_glob )) && walker_opts+=',hidden'
          opts+=(
            --walker=$walker_opts
            --walker-skip=.git,node_modules,.cache,.svn
          )
        else
          () {
            emulate -L zsh
            # Set dot_glob in case the value of find-flags depends on it (via `zstyle -e`).
            # Ideally we should run this with user options.
            (( dot_glob )) && setopt dot_glob
            local -a bin
            zstyle -a :z4m:${WIDGET#z4m-} find-command bin
            if (( ! $#bin )) && (( $+commands[bfs] )); then
              opts+=(--no-sort)
            fi
          }
        fi

        local cursor_y cursor_x
        -z4m-get-cursor-pos || return

        if (( _z4m_can_save_restore_screen )); then
          opts+=(--no-clear)
          if { (( height <= cursor_y - 1 )) && zstyle -T :z4m: prompt-at-bottom } ||
             (( cursor_y - 1 > LINES - cursor_y && cursor_y - 1 > 4 )) &&
             { (( height > LINES - cursor_y )) || zstyle -T :z4m: prompt-at-bottom }; then
            (( height <= cursor_y - 1 )) || (( height = cursor_y - 1 ))
            local move=$'\e[0m\e['$((cursor_y-height))';1H'
            opts+=(--layout=default)
          elif (( LINES - cursor_y > 4 )); then
            (( height <= LINES - cursor_y )) || (( height = LINES - cursor_y ))
            local move=$'\e[0m\n\r'
            opts+=(--layout=reverse)
          else
            local -i extra=$((height - LINES + cursor_y))
            print -rnu $_z4m_tty_fd -- ${(pl:$height::\n:)} || return
            (( cursor_y += LINES - cursor_y - height ))
            local move=$'\e[0m\e['$((cursor_y+1))';1H'
            opts+=(--layout=reverse)
          fi
          local _z4m_saved_screen
          -z4m-save-screen || return
        else
          print -u $_z4m_tty_fd || return
          local move=
          opts+=(--layout=reverse)
        fi

        opts+=(--height=$height)

        {
          local choice
          choice=$(
            unsetopt pipe_fail
            exec 2>/dev/null
            {
              print -r -- $sysparams[pid]
              print -rC1 -- $dirs
              -z4m-find $dot_glob 1 $non_empty | command sed -n '/\/.*\// s/^..//p'
            } | {
              local -a pids
              IFS=' ' builtin read -rA pids || exit
              print -r -- $pids $sysparams[pid] || exit
              -z4m-present-files $list_colors $list_types 0
            } | {
              local -a pids
              IFS=' ' builtin read -rA pids || pids=()
              print -rnu $_z4m_tty_fd -- $move
              -z4m-cursor-show
              2>&$_z4m_tty_fd -z4m-fzf $opts
              (( $#pids )) && builtin kill -- $pids
            } always {
              -z4m-cursor-hide
            })
          [[ -n $choice ]] || return
          choice=("${(@f)choice}")
          [[ -n $choice[1] ]] && again=1
          cd -- ${choice[2]%%$'\0'*} 2>/dev/null || return
          redraw=1
        } always {
          if (( _z4m_can_save_restore_screen )); then
            -z4m-restore-screen
            print -rn -- $'\e[0m\e['$cursor_y';'$cursor_x'H'
          else
            builtin echoti cuu 1
            (( cursor_x > 1 )) && builtin echoti cuf $((cursor_x-1))
          fi
        }
      } always {
        zle -R
      }
    } || return
    (( redraw )) && -z4m-redraw-prompt 1
    (( again )) || break
  done
} always {
  -z4m-cursor-show
}
