#!/usr/bin/env zsh

[[ -v _z4m_tty_fd ]] || return

builtin echoti civis >&$_z4m_tty_fd
local -i cursor_x cursor_y
-z4m-get-cursor-pos || cursor_y=0
local -i pad_lines=$((2 * LINES - cursor_y - 1))
builtin print -rnu $_z4m_tty_fd -- "${(pl:$pad_lines::\n:)}"
builtin zle -I
builtin zle -R
-z4m-cursor-show
