#!/bin/sh

if '[' '-n' "${ZSH_VERSION-}" ']'; then
  'emulate' 'sh' '-o' 'no_aliases' '-o' 'no_glob'
else
  'set' '-f'
fi

_z4m_bypass=''
_z4m_bypass_reason=''

_z4m_ssh_apply_cwd() {
  _z4m_ssh_cwd="${Z4M_SSH_CWD-}"
  '[' '-n' "$_z4m_ssh_cwd" ']' || 'return' '0'

  case "$_z4m_ssh_cwd" in
    '~')
      _z4m_ssh_cwd="$HOME"
      ;;
    '~/'*)
      _z4m_ssh_cwd="$HOME/${_z4m_ssh_cwd#~/}"
      ;;
    '$HOME'|'${HOME}')
      _z4m_ssh_cwd="$HOME"
      ;;
    '$HOME/'*)
      _z4m_ssh_cwd="$HOME/${_z4m_ssh_cwd#\$HOME/}"
      ;;
    '${HOME}/'*)
      _z4m_ssh_cwd="$HOME/${_z4m_ssh_cwd#\$\{HOME\}/}"
      ;;
    '$ZDOTDIR'|'${ZDOTDIR}')
      _z4m_ssh_cwd="${ZDOTDIR:-$HOME}"
      ;;
    '$ZDOTDIR/'*)
      _z4m_ssh_cwd="${ZDOTDIR:-$HOME}/${_z4m_ssh_cwd#\$ZDOTDIR/}"
      ;;
    '${ZDOTDIR}/'*)
      _z4m_ssh_cwd="${ZDOTDIR:-$HOME}/${_z4m_ssh_cwd#\$\{ZDOTDIR\}/}"
      ;;
    /*)
      ;;
    *)
      _z4m_ssh_cwd="$HOME/$_z4m_ssh_cwd"
      ;;
  esac

  if ! 'cd' -- "$_z4m_ssh_cwd" 2>'/dev/null'; then
    >&2 'printf' '\033[33mz4m\033[0m: unable to enter remote cwd: \033[31m%s\033[0m\n' "$_z4m_ssh_cwd"
    'return' '1'
  fi

  'unset' 'Z4M_SSH_CWD' 2>'/dev/null' || :
}

for _z4m_ssh_cmd in 'tar' 'tail' 'rm' 'mkdir' 'mv' 'cp' 'cat' 'uname' 'tr'; do
  if ! command -v "$_z4m_ssh_cmd" >'/dev/null' 2>&1; then
    _z4m_bypass='1'
    _z4m_bypass_reason="missing command: $_z4m_ssh_cmd"
    'break'
  fi
done

if '[' '-z' "$_z4m_bypass" ']'; then
  {
    _z4m_ssh_platform="$('command' 'uname' '-sm')" &&
      _z4m_ssh_platform="$('printf' '%s' "$_z4m_ssh_platform" | 'command' 'tr' '[A-Z]' '[a-z]')" ||
      _z4m_ssh_platform=''
  } 2>'/dev/null'

  case "$_z4m_ssh_platform" in
    'darwin arm64');;
    'darwin x86_64');;
    'linux aarch64');;
    'linux armv6l');;
    'linux armv7l');;
    'linux armv8l');;
    'linux x86_64');;
    'linux i686');;
    *)
      _z4m_bypass='1'
      _z4m_bypass_reason="unsupported platform: ${_z4m_ssh_platform:-unknown}"
      ;;
  esac
fi

if '[' '-n' "$_z4m_bypass" ']'; then
  command -v 'rm' >'/dev/null' 2>&1 && 'command' 'rm' '-f' '--' "$0"

  export TERM=^TERM^

  if '[' '-n' "$_z4m_bypass_reason" ']'; then
    >&2 'printf' '\033[33mz4m\033[0m: falling back to remote login shell (%s)\n' "$_z4m_bypass_reason"
  else
    >&2 'printf' '\033[33mz4m\033[0m: falling back to remote login shell\n'
  fi

  _z4m_ssh_apply_cwd || :

  if '[' '-x' "${SHELL-}" ']'; then
    'exec' "$SHELL" '-l'
  fi

  'exec' 'sh' '-l'
fi

_z4m_ssh_error() {
  >&2 'printf' '\n'
  >&2 'printf' '\033[33mz4m\033[0m: failed to start \033[32mzsh\033[0m on \033[1m%s\033[0m\n' ^SSH_HOST^
  >&2 'printf' '\n'
  >&2 'printf' 'See error messages above to identify the culprit.\n'
  >&2 'printf' '\n'
}

_z4m_ssh_mktemp() {
  if '[' '-n' "${TMPDIR-}" '-a' '-d' "${TMPDIR-}" '-a' '-w' "${TMPDIR-}" ']'; then
    'set' '--' "$TMPDIR"
  else
    'set' '--' '/tmp'
  fi
  if command -v 'mktemp' >'/dev/null' 2>&1; then
    _z4m_ssh_tmp="$('command' 'mktemp' '-d' -- "$1"/z4m-ssh.XXXXXXXXXX)"
  else
    _z4m_ssh_tmp="$1"/z4m-ssh.tmp."$$"
    '[' '!' '-e' "$_z4m_ssh_tmp" ']' || 'command' 'rm' '-rf' '--' "$_z4m_ssh_tmp" || 'exit'
    'command' 'mkdir' '-p' '--' "$_z4m_ssh_tmp" || 'exit'
  fi
}

_z4m_ssh_cleanup='"trap" "-" "HUP" "INT" "TERM" "EXIT"; _z4m_ssh_tmp="${_z4m_ssh_tmp-}"; [ -n "$_z4m_ssh_tmp" ] && "command" "rm" "-rf" "--" "$_z4m_ssh_tmp" 2>"/dev/null"'
'trap' "$_z4m_ssh_cleanup; 'exit' '129'" 'HUP'
'trap' "$_z4m_ssh_cleanup; 'exit' '130'" 'INT'
'trap' "$_z4m_ssh_cleanup; 'exit' '143'" 'TERM'
'trap' "$_z4m_ssh_cleanup; _z4m_ssh_error" 'EXIT'

z4m_min_version=^MIN_VERSION^
z4m_ssh_client=^SSH_CLIENT^
z4m_ssh_host=^SSH_HOST^

'export' Z4M_SSH="$z4m_min_version":"$z4m_ssh_client":"$z4m_ssh_host"
'export' P9K_TTY='old'

^PRELUDE^

_z4m_ssh_tar_x_opt=
if _z4m_ssh_tar_v="$('command' 'tar' '--version' 2>&1)"; then
  case "$_z4m_ssh_tar_v" in
    *'GNU tar'*)
      _z4m_ssh_tar_x_opt='--warning=no-unknown-keyword --warning=no-timestamp --no-same-owner'
      ;;
  esac
fi

_z4m_ssh_mktemp

'command' 'tail' '-c' '+'^DUMP_POS^ '--' "$0" \
  | 'command' 'tar' '-C' "$_z4m_ssh_tmp" $_z4m_ssh_tar_x_opt '-xzf' '-' || 'exit'

'command' 'rm' '-f' '--' "$0" || 'exit'

_z4m_ssh_src='0'

for _z4m_ssh_dst in ^SEND_TO^; do
  _z4m_ssh_src="$((_z4m_ssh_src + 1))"
  case "$_z4m_ssh_dst" in
    '')
      >&2 'printf' '\033[33mz4m\033[0m: empty remote destination after expansion\n'
      'exit' '1'
      ;;
    */)
      >&2 'printf' '\033[33mz4m\033[0m: remote destination ends with \033[1m/\033[0m: \033[31m%s\033[0m\n' "$_z4m_ssh_dst"
      'exit' '1'
      ;;
    /*)
      ;;
    *)
      _z4m_ssh_dst="$HOME/$_z4m_ssh_dst"
      ;;
  esac

  if '[' '-e' "$_z4m_ssh_tmp"/"$_z4m_ssh_src" ']'; then
    _z4m_ssh_dir="${_z4m_ssh_dst%/*}"
    if '[' '!' '-e' "$_z4m_ssh_dir" ']'; then
      'command' 'mkdir' '-p' '--' "$_z4m_ssh_dir" || 'exit'
    fi
    if '[' '-e' "$_z4m_ssh_dst" ']'; then
      'command' 'rm' '-rf' '--' "$_z4m_ssh_dst" || 'exit'
    fi
    if ! 'command' 'mv' '-f' '--' "$_z4m_ssh_tmp"/"$_z4m_ssh_src" "$_z4m_ssh_dst" 2>'/dev/null'; then
      'command' 'cp' '-rf' '--' "$_z4m_ssh_tmp"/"$_z4m_ssh_src" "$_z4m_ssh_dst" || 'exit'
    fi
  fi
done

'command' 'rm' '-rf' '--' "$_z4m_ssh_tmp" || 'exit'

if '[' '!' '-d' "$Z4M"/tmp '-o' '!' '-d' "$Z4M"/stickycache ']'; then
  'command' 'mkdir' '-p' '--' "$Z4M"/tmp "$Z4M"/stickycache || 'exit'
fi

_z4m_ssh_apply_cwd || :

^RUN^

_z4m_ssh_ret="$?"
'trap' '-' 'HUP' 'INT' 'TERM' 'EXIT'
'exit' "${_z4m_ssh_ret:-1}"
